# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: cd KwikKoderUI && npm ci
      - name: Build
        run: cd KwikKoderUI && npm run build:ci
      - name: Test
        run: cd KwikKoderUI && npm run test:ci
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: KwikKoderUI/dist
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: KwikKoderUI/coverage
          
  sonarcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: KwikKoderUI  
        args: >
          -Dsonar.organization=210503-reston-kwikkoder
          -Dsonar.projectKey=210503-Reston-KwikKoder_Front-End
          -Dsonar.tests=src
          -Dsonar.test.inclusions=**/*.spec.ts
          -Dsonar.ts.tslintconfigpath=tslint.json
          -Dsonar.javascript.lcov.reportPaths=coverage/Ang-GACD-UI/lcov.info
          -Dsonar.typescript.exclusions=**/node_modules/**,**/typings.d.ts,**/main.ts,**/environments/environment*.ts,**/*routing.module.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Download code coverage results
      uses: actions/download-artifact@v1
      with: 
        name: deploy_coverage
        path: Ang-GACD-UI/lcov-report
        
    
